<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLWn5MLs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLWn5MLs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLWn5MLs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLWn5MLs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLWn5MLs\App_KernelDevDebugContainer([
    'container.build_hash' => 'LWn5MLs',
    'container.build_id' => '7818170f',
    'container.build_time' => 1703731035,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLWn5MLs');
