<?php

namespace ContainerME4mlmG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJuegoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XtV2dzD.App\Entity\Juego' shared service.
     *
     * @return \App\Entity\Juego
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.XtV2dzD": it references class "App\\Entity\\Juego" but no such service exists.');
    }
}
