<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFdVxMFy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFdVxMFy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFdVxMFy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFdVxMFy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFdVxMFy\App_KernelDevDebugContainer([
    'container.build_hash' => 'FdVxMFy',
    'container.build_id' => '2f57e380',
    'container.build_time' => 1677714931,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFdVxMFy');
