<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerME4mlmG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerME4mlmG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerME4mlmG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerME4mlmG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerME4mlmG\App_KernelDevDebugContainer([
    'container.build_hash' => 'ME4mlmG',
    'container.build_id' => 'affc65e2',
    'container.build_time' => 1702016603,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerME4mlmG');
